///////////////////////////////////////////////////////////
//  BaseVoltage.cs
//  Implementation of the Class BaseVoltage
//  Generated by Enterprise Architect
//  Created on:      09-Jul-2016 12:00:25 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Core {
    [Serializable]
    /// <summary>
    /// Defines a system base voltage which is referenced.
    /// </summary>
    public class BaseVoltage : IdentifiedObject {

		/// <summary>
		/// The power system resource's base voltage.
		/// </summary>
		public float nominalVoltage {
            get; set; }
		/// <summary>
		/// All conducting equipment with this base voltage.  Use only when there is no
		/// voltage level container used and only one base voltage applies.  For example,
		/// not used for transformers.
		/// </summary>
		public List<ConductingEquipment> ConductingEquipment = new List<Core.ConductingEquipment>();

		public BaseVoltage(){
            

        }

		~BaseVoltage(){

		}

	}//end BaseVoltage

}//end namespace Core