///////////////////////////////////////////////////////////
//  RotatingMachine.cs
//  Implementation of the Class RotatingMachine
//  Generated by Enterprise Architect
//  Created on:      09-Jul-2016 12:00:50 AM
//  Original author: tsaxton
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



using CIM.IEC61970.Base.Core;
namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// A rotating machine which may be used as a generator or motor.
	/// </summary>
	public class RotatingMachine : ConductingEquipment {

		/// <summary>
		/// Power factor (nameplate data). It is primarily used for short circuit data
		/// exchange according to IEC 60909.
		/// </summary>
		public float ratedPowerFactor
        {
            get; set;
        }
        /// <summary>
        /// Nameplate apparent power rating for the unit.
        /// </summary>
        public float ratedS
        {
            get; set;
        }
        /// <summary>
        /// Rated voltage (nameplate data, Ur in IEC 60909-0). It is primarily used for
        /// short circuit data exchange according to IEC 60909.
        /// </summary>
        public float ratedU
        {
            get; set;
        }

        public RotatingMachine(){

		}

		~RotatingMachine(){

		}

	}//end RotatingMachine

}//end namespace Wires