///////////////////////////////////////////////////////////
//  SynchronousMachineOperatingMode.cs
//  Implementation of the Enumeration SynchronousMachineOperatingMode
//  Generated by Enterprise Architect
//  Created on:      09-Jul-2016 12:00:50 AM
///////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.IO;



namespace CIM.IEC61970.Base.Wires {
	/// <summary>
	/// Synchronous machine operating mode.
	/// </summary>
	public enum SynchronousMachineOperatingMode : int {

		generator,
		condenser,
		motor

	}//end SynchronousMachineOperatingMode

}//end namespace Wires